"use strict";
require("./less/main.less");
var React = require('react');
var ReactDOM = require('react-dom');
var component_1 = require('./component');
var redux_1 = require('redux');
var react_redux_1 = require('react-redux');
var initialState = { item_name: 0 };
var store = redux_1.createStore(function (data) { return data; }, initialState);
var store2 = redux_1.createStore(function (data) { return data; }, { item_name: 999 });
ReactDOM.render(React.createElement(react_redux_1.Provider, {store: store}, React.createElement(component_1.default, null)), document.getElementById('app'));
ReactDOM.render(React.createElement(react_redux_1.Provider, {store: store2}, React.createElement(component_1.default, null)), document.getElementById('app2'));
window['$'] = $;
